# Generated by Django 4.2.30 on 2026-06-27 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lessonfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="student_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="student_slug",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="booking",
            name="tutor_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="tutor_slug",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="student_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="student_slug",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="receipt",
            name="billing_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="receipt",
            name="billing_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="receipt",
            name="billing_line1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="receipt",
            name="billing_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="receipt",
            name="billing_postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="receipt",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="student_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="receipt",
            name="student_slug",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="booking",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutor_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="credittransaction",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
