# Generated by Django 4.2.30 on 2026-06-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_backfill_history_snapshots"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_session_id", ""), _negated=True),
                fields=("stripe_session_id",),
                name="unique_stripe_session",
            ),
        ),
    ]
