# Generated by Django 4.2.30 on 2026-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_receipt_unique_stripe_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_intro",
            field=models.BooleanField(default=False),
        ),
    ]
