# Generated by Django 4.2.30 on 2026-06-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_booking_guest_email_booking_guest_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
