# Generated by Django 5.2.15 on 2026-06-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_booking_guest_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="credit_floor",
            field=models.IntegerField(default=-10),
        ),
        migrations.AddField(
            model_name="user",
            name="settle_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="packs_json",
            field=models.TextField(
                default='[{"n":1,"price":"€32","each":"€32 / session","feat":false},{"n":5,"price":"€145","each":"€29 / session","feat":false},{"n":10,"price":"€270","each":"€27 / session","feat":true,"tag":"Popular"}]'
            ),
        ),
    ]
