# Generated by Django 5.2.15 on 2026-06-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_sitesettings_credit_floor_user_settle_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="popular_n",
            field=models.IntegerField(default=10),
        ),
    ]
