# Generated by Django 5.2.15 on 2026-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_sitesettings_popular_n"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancel_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
