# Generated by Django 4.2.30 on 2026-07-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_booking_cancel_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="core.credittransaction",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="core.receipt",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="stripe_refund_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
