from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_view, name='landing'),
    path('app/', views.app_view, name='app'),
    path('login/', views.login_view, name='login'),
    path('impressum/', views.impressum_view, name='impressum'),
    path('datenschutz/', views.datenschutz_view, name='datenschutz'),
    path('intro/', views.intro_view, name='intro'),
    path('cancel/<str:token>/', views.booking_cancel_view, name='booking_cancel'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', views.sitemap_xml, name='sitemap_xml'),
    path('api/intro-bookings/', views.api_intro_booking),
    path('api/login/', views.api_login),
    path('api/logout/', views.api_logout),
    path('api/bookings/', views.api_bookings),
    path('api/bookings/<int:pk>/', views.api_booking_detail),
    path('api/credits/<str:slug>/', views.api_credits),
    path('api/transactions/<int:txn_id>/cancel/', views.api_cancel_transaction),
    path('api/receipts/<str:number>/pdf/', views.api_receipt_pdf),
    path('api/checkout/', views.api_checkout),
    path('api/checkout/confirm/', views.api_checkout_confirm),
    path('api/stripe/webhook/', views.api_stripe_webhook),
    path('api/settle/', views.api_settle),
    path('api/students/<str:slug>/settle-link/', views.api_settle_link),
    path('settle/<str:token>/', views.settle_page, name='settle'),
    path('settle/<str:token>/checkout/', views.api_settle_token_checkout),
    path('api/users/me/billing/', views.api_billing),
    path('api/availability/', views.api_availability),
    path('api/custom-times/', views.api_custom_times),
    path('api/notes/<str:slug>/', views.api_notes),
    path('api/lessons/<str:slug>/', views.api_lessons),
    path('api/lesson-files/download/<int:file_id>/', views.api_lesson_file_download),
    path('api/lesson-files/<int:file_id>/', views.api_lesson_file_detail),
    path('api/lesson-files/<str:lesson_id>/', views.api_lesson_files),
    path('api/users/', views.api_users),
    path('api/users/<str:slug>/', views.api_user_detail),
    path('api/settings/', views.api_settings),
]
